// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_live.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy7nbMnuw1bU459ctNsgjvsYRsGcJaKqM',
    appId: '1:1079093619503:web:4e8ceab37e0791763acfda',
    messagingSenderId: '1079093619503',
    projectId: 'dayagenda-live',
    authDomain: 'dayagenda-live.firebaseapp.com',
    storageBucket: 'dayagenda-live.firebasestorage.app',
    measurementId: 'G-P1ZRXEJSBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB4GjutXU3j0rtpQq5fEdQJ2l1INNZ0GI',
    appId: '1:1079093619503:android:c4b3b93073001f4a3acfda',
    messagingSenderId: '1079093619503',
    projectId: 'dayagenda-live',
    storageBucket: 'dayagenda-live.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRejmqwZxra6eYFFRWAXXMMZ3KqH-4jOI',
    appId: '1:1079093619503:ios:86e91e7d41b168ea3acfda',
    messagingSenderId: '1079093619503',
    projectId: 'dayagenda-live',
    storageBucket: 'dayagenda-live.firebasestorage.app',
    iosBundleId: 'com.ambee.dayagenda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRejmqwZxra6eYFFRWAXXMMZ3KqH-4jOI',
    appId: '1:1079093619503:ios:86e91e7d41b168ea3acfda',
    messagingSenderId: '1079093619503',
    projectId: 'dayagenda-live',
    storageBucket: 'dayagenda-live.firebasestorage.app',
    iosBundleId: 'com.ambee.dayagenda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDTylUcTgAUfNQgNZIdPKwjaoXoMziUlQ',
    appId: '1:1079093619503:web:63615457e64f3ac33acfda',
    messagingSenderId: '1079093619503',
    projectId: 'dayagenda-live',
    authDomain: 'dayagenda-live.firebaseapp.com',
    storageBucket: 'dayagenda-live.firebasestorage.app',
    measurementId: 'G-V0NXHDQQ0J',
  );
}
