// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyY59uK29Ml-qaBVpVNbhHL5Ru3uwYXKM',
    appId: '1:278733194356:web:23a98e10609ff258247d21',
    messagingSenderId: '278733194356',
    projectId: 'dayagenda-dev',
    authDomain: 'dayagenda-dev.firebaseapp.com',
    storageBucket: 'dayagenda-dev.firebasestorage.app',
    measurementId: 'G-LPTNX2G2E0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ9qatW07zUexZhmZmC8XN17g7pamdKCs',
    appId: '1:278733194356:android:efb1962d711b9b7b247d21',
    messagingSenderId: '278733194356',
    projectId: 'dayagenda-dev',
    storageBucket: 'dayagenda-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOzW7FYm4Qe4xIvjWv9esJBm_zQCLPoyM',
    appId: '1:278733194356:ios:d6a5e86280dd8084247d21',
    messagingSenderId: '278733194356',
    projectId: 'dayagenda-dev',
    storageBucket: 'dayagenda-dev.firebasestorage.app',
    iosBundleId: 'com.ambee.dayagenda.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOzW7FYm4Qe4xIvjWv9esJBm_zQCLPoyM',
    appId: '1:278733194356:ios:d6a5e86280dd8084247d21',
    messagingSenderId: '278733194356',
    projectId: 'dayagenda-dev',
    storageBucket: 'dayagenda-dev.firebasestorage.app',
    iosBundleId: 'com.ambee.dayagenda.dev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt9AyAxDkv4VK_W2l4YeoZg3mIxGvmtcM',
    appId: '1:278733194356:web:82669caf5d456522247d21',
    messagingSenderId: '278733194356',
    projectId: 'dayagenda-dev',
    authDomain: 'dayagenda-dev.firebaseapp.com',
    storageBucket: 'dayagenda-dev.firebasestorage.app',
    measurementId: 'G-7LVK2CEPJN',
  );
}
