require 'xcodeproj'

platform :ios, '13.0'
install! 'cocoapods', :disable_input_output_paths => true
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug-dev'   => :debug,
  'Debug-live'  => :debug,
  'Profile-dev' => :release,
  'Profile-live'=> :release,
  'Release-dev' => :release,
  'Release-live'=> :release,
}

pod 'AppAuth',         '~> 1.7.6'
pod 'GoogleUtilities', '~> 7.13.3'

def flutter_root
  gen = File.expand_path('Flutter/Generated.xcconfig', __dir__)
  raise "#{gen} missing—run `flutter pub get` first." unless File.exist?(gen)
  File.foreach(gen) do |line|
    if (m = line.match(/FLUTTER_ROOT\=(.*)/))
      return m[1].strip
    end
  end
  raise "FLUTTER_ROOT not found in Generated.xcconfig."
end

require File.expand_path('packages/flutter_tools/bin/podhelper', flutter_root)
flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))
end

post_install do |installer|
  installer.pods_project.targets.each do |t|
    flutter_additional_ios_build_settings(t)
  end
end